server:
  port: 8083
  
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b541d544e570dd0e355c
            client-secret: d73c9299cd22e06a8d6d6970cae0bd687a0d9b3d
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: core_route
          uri: lb://core-management
          predicates:
          - Path=/core/**
          filters:
          - RewritePath=/core/(?<path>.*), /$\{path}
        - id: user_route
          uri: lb://user-management
          predicates:
          - Path=/user/**
          filters:
          - RewritePath=/user/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
          - Path=/v3/api-docs/**
          filters:
          - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

info:
  app:
    name: ${spring.application.name}
