server:
  port: 8083

spring:
  security:
    user:
      name:
        user
      password:
        password
  cloud:
    gateway:
      routes:
        - id: users_route
          uri: lb://core-management
          predicates:
            - Path=/users/**
        - id: transfer_list_route
          uri: lb://core-management
          predicates:
            - Path=/transfer-list/**
        - id: players_route
          uri: lb://core-management
          predicates:
            - Path=/players/**
        - id: transactions_route
          uri: lb://core-management
          predicates:
            - Path=/transactions/**
        - id: user_route
          uri: lb://user-management
          predicates:
            - Path=/users/**
          
          

info:
  app:
    name: ${spring.application.name}
