server:
  error:
    include-stacktrace: never

default-balance: 60000
user-service-url: http://localhost:8081/users
elasticsearch:
  url: localhost:9200
fantasy-team-mail-queue: fantasy-team-mail-queue

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/core_management_db
    username: '{cipher}3ebeb68cf47b303b1dcefa6400b85f42f20b8c45960c117486cea069b9f2af15'
    password: '{cipher}eeea6f17e40e65c284f7b012f1a1fd107265bebaa3862a52622feeefc5915a77'
